import type { Game, Scene } from '../../core/Game';
import type { GameTime } from '../../core/Time';
import { Action } from '../../input/Actions';
import type { Ctx } from '../../render/draw';
import { rgba } from '../../render/draw';
import { displayText, label, PALETTE, FONT_UI, wrapText } from '../ui';

interface CreditLine {
  kind: 'title' | 'head' | 'line' | 'small' | 'gap';
  text?: string;
  color?: string;
}

/**
 * Scrolling credits.
 *
 * The originality statement is here rather than buried in a file, because it is
 * the honest answer to "where did the art and music come from": nowhere. It is
 * all generated by the code in this repository at runtime.
 */
const CREDITS: CreditLine[] = [
  { kind: 'title', text: 'GLASS JAW' },
  { kind: 'small', text: 'CHAMPIONSHIP BOXING' },
  { kind: 'gap' }, { kind: 'gap' },

  { kind: 'head', text: 'DESIGN AND CODE' },
  { kind: 'line', text: 'Original game systems, combat, AI and presentation' },
  { kind: 'gap' },

  { kind: 'head', text: 'ART' },
  { kind: 'line', text: 'Every character, arena and effect in this game is' },
  { kind: 'line', text: 'drawn procedurally by the renderer at runtime.' },
  { kind: 'line', text: 'There are no image files anywhere in this project.' },
  { kind: 'gap' },

  { kind: 'head', text: 'MUSIC AND SOUND' },
  { kind: 'line', text: 'All music is composed as note patterns and played' },
  { kind: 'line', text: 'through a Web Audio synthesiser written for this game.' },
  { kind: 'line', text: 'Every punch, bell, voice and crowd reaction is' },
  { kind: 'line', text: 'synthesised from oscillators and shaped noise.' },
  { kind: 'line', text: 'No samples. No recordings. No audio files.' },
  { kind: 'gap' },

  { kind: 'head', text: 'THE ROSTER' },
  { kind: 'line', text: 'Paco "Panqueque" Delgado  ·  Mimi "La Mime" Moreau' },
  { kind: 'line', text: 'Bruno "Il Muro" Bellini  ·  Kip "Twelve Volts" Turbo' },
  { kind: 'line', text: 'Olga "The Anvil" Voronova  ·  Kwame "Sunrise" Adeyemi' },
  { kind: 'line', text: 'Sven "Timber" Hammarlund  ·  Rico "Ricochet" Vega' },
  { kind: 'line', text: 'Hiroshi "Kagemusha" Tanabe  ·  Duke "The Sergeant" Marlow' },
  { kind: 'line', text: 'Zara "Mirage" Nazari  ·  Bruiser "The Mauler" McGraw' },
  { kind: 'line', text: 'Augusto "Velho Leão" Silva  ·  Niko "The Surgeon" Zarkov' },
  { kind: 'line', text: 'Nia "Tempest" Okonjo  ·  Maxim "The Machine" Kane' },
  { kind: 'gap' },
  { kind: 'line', text: 'and, in the blue corner,' },
  { kind: 'line', text: 'Rusty "Kid Comet" Kovac', color: PALETTE.gold },
  { kind: 'gap' }, { kind: 'gap' },

  { kind: 'head', text: 'THIRD-PARTY SOFTWARE' },
  { kind: 'line', text: 'TypeScript  —  Apache-2.0' },
  { kind: 'line', text: 'Vite  —  MIT' },
  { kind: 'line', text: 'Playwright (testing only)  —  Apache-2.0' },
  { kind: 'small', text: 'Build tooling only. None of it ships inside the game.' },
  { kind: 'small', text: 'Full details in CREDITS.md and LICENSES.md.' },
  { kind: 'gap' },

  { kind: 'head', text: 'FONTS' },
  { kind: 'line', text: 'System fonts only, via CSS generic families.' },
  { kind: 'small', text: 'No font files are bundled or downloaded.' },
  { kind: 'gap' }, { kind: 'gap' },

  { kind: 'head', text: 'A NOTE ON INSPIRATION' },
  { kind: 'line', text: 'Glass Jaw is an original game that admires a genre:' },
  { kind: 'line', text: 'the one-on-one arcade boxing game, where you win by' },
  { kind: 'line', text: 'reading a pattern rather than by mashing buttons.' },
  { kind: 'gap' },
  { kind: 'line', text: 'Its characters, art, music, sound, text and code are' },
  { kind: 'line', text: 'original to this project. Nothing here is copied,' },
  { kind: 'line', text: 'traced, sampled or ported from any other game.' },
  { kind: 'gap' }, { kind: 'gap' },

  { kind: 'head', text: 'THANK YOU FOR PLAYING' },
  { kind: 'gap' },
  { kind: 'line', text: 'Now go and find out what Kane does in phase five.', color: PALETTE.gold },
  { kind: 'gap' }, { kind: 'gap' }, { kind: 'gap' },
];

export class CreditsScreen implements Scene {
  readonly name = 'credits';
  private y = 0;
  private t = 0;
  private speed = 46;
  private totalHeight = 0;

  constructor(private readonly game: Game) {}

  enter(): void {
    this.y = this.game.renderer.dh;
    this.game.audio.playMusic('career', 0.8);
  }

  exit(): void { /* the next screen sets its own music */ }

  update(_dt: number, _time: GameTime): void {
    const i = this.game.input;
    if (i.justPressed(Action.Cancel) || i.justPressed(Action.Confirm)) {
      this.game.audio.play('uiBack');
      this.game.goPop();
      return;
    }
    // Hold down to speed through, up to scroll back.
    this.speed = i.isDown(Action.MenuDown) ? 320 : i.isDown(Action.MenuUp) ? -260 : 46;
  }

  updateRaw(rawDt: number): void {
    this.t += rawDt;
    this.y -= this.speed * rawDt;
    const min = -this.totalHeight - 100;
    if (this.y < min) this.y = this.game.renderer.dh;
    if (this.y > this.game.renderer.dh) this.y = this.game.renderer.dh;
  }

  render(ctx: Ctx, _alpha: number, _time: GameTime): void {
    const { dw, dh } = this.game.renderer;

    const g = ctx.createLinearGradient(0, 0, 0, dh);
    g.addColorStop(0, '#120d1e');
    g.addColorStop(1, '#05030a');
    ctx.fillStyle = g;
    ctx.fillRect(0, 0, dw, dh);

    ctx.save();
    ctx.globalCompositeOperation = 'lighter';
    ctx.globalAlpha = 0.06;
    for (let i = 0; i < 5; i++) {
      const cx = dw / 2 + Math.sin(this.t * 0.3 + i) * dw * 0.3;
      const rg = ctx.createRadialGradient(cx, dh * 0.5, 20, cx, dh * 0.5, dh * 0.7);
      rg.addColorStop(0, 'rgba(255,209,102,0.8)');
      rg.addColorStop(1, 'rgba(0,0,0,0)');
      ctx.fillStyle = rg;
      ctx.fillRect(0, 0, dw, dh);
    }
    ctx.restore();

    let cy = this.y;
    const cx = dw / 2;
    const maxW = Math.min(900, dw * 0.8);

    for (const line of CREDITS) {
      switch (line.kind) {
        case 'gap': cy += 30; break;
        case 'title':
          if (cy > -140 && cy < dh + 140) {
            displayText(ctx, line.text!, cx, cy, 96, PALETTE.gold, {
              outlineWidth: 16, shadow: PALETTE.orange,
            });
          }
          cy += 118;
          break;
        case 'head':
          if (cy > -60 && cy < dh + 60) {
            displayText(ctx, line.text!, cx, cy, 32, line.color ?? PALETTE.orange, { outlineWidth: 6 });
          }
          cy += 54;
          break;
        case 'line': {
          const lines = wrapText(ctx, line.text!, maxW, `600 22px ${FONT_UI}`);
          for (const ln of lines) {
            if (cy > -40 && cy < dh + 40) {
              label(ctx, ln, cx, cy, 22, line.color ?? PALETTE.text, { align: 'center', weight: 600 });
            }
            cy += 32;
          }
          break;
        }
        case 'small':
          if (cy > -40 && cy < dh + 40) {
            label(ctx, line.text!, cx, cy, 16, line.color ?? PALETTE.dim, { align: 'center', weight: 600 });
          }
          cy += 26;
          break;
      }
    }
    this.totalHeight = cy - this.y;

    // Edge fades so lines enter and leave softly.
    const top = ctx.createLinearGradient(0, 0, 0, 150);
    top.addColorStop(0, 'rgba(10,7,16,1)');
    top.addColorStop(1, 'rgba(10,7,16,0)');
    ctx.fillStyle = top;
    ctx.fillRect(0, 0, dw, 150);
    const bot = ctx.createLinearGradient(0, dh - 150, 0, dh);
    bot.addColorStop(0, 'rgba(5,3,10,0)');
    bot.addColorStop(1, 'rgba(5,3,10,1)');
    ctx.fillStyle = bot;
    ctx.fillRect(0, dh - 150, dw, 150);

    label(ctx, 'HOLD ↓ to speed up    ↑ to rewind    ESC to go back',
      cx, dh - 34, 15, rgba(PALETTE.dim, 0.8), { align: 'center', weight: 700 });
  }
}
