"""Image assets (generated by tools/make_textures.py), loaded and packed."""

import os
import bpy

HERE = os.path.dirname(os.path.abspath(__file__))
TEX_DIR = os.path.normpath(os.path.join(HERE, "..", "textures"))


def image(name, colorspace='sRGB'):
    """Load textures/<name> once and pack it into the .blend."""
    img = bpy.data.images.get(name)
    if img is None:
        path = os.path.join(TEX_DIR, name)
        if not os.path.exists(path):
            raise FileNotFoundError(f"{path} missing - run tools/make_textures.py")
        img = bpy.data.images.load(path, check_existing=True)
        img.name = name
        img.colorspace_settings.name = colorspace
        img.pack()
    return img
